DROP DATABASE mydb1 ;
DROP DATABASE mydb2 ;
DROP DATABASE mydb3 ;
DROP DATABASE mydb4 ;
DROP DATABASE mydb5 ;
DROP DATABASE mydb6 ;
DROP DATABASE mydb7 ;
DROP DATABASE mydb8 ;
DROP DATABASE mydb9 ;

DROP DATABASE emr50k ;
DROP DATABASE emr100k ;
DROP DATABASE install ;
DROP DATABASE synthea ;

DROP ROLE student;
DROP ROLE student_grp;


