name: build-nurs6293-desktop

on:
  release: 
    types: [prereleased]

jobs:
  docker-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull repository
        uses: actions/checkout@v4
      
      - name: Pull artifact binaries
        run: gh release download v1.1 --repo Andrew0Hill/nurs6293_binaries --pattern '*.tar.gz' --pattern '*.jar' --dir ./nurs6293_desktop/artifacts
        env:
          GH_TOKEN: ${{ secrets.BINARY_REPO_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          context: ./nurs6293_desktop
          push: true
          tags: |
            andrew2hill/nurs6293_desktop_dev:${{ github.ref_name }}
            andrew2hill/nurs6293_desktop_dev:latest
