name: build-nurs6293-database

on:
  release: 
    types: [published]

jobs:
  docker-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Pull repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          context: ./nurs6293_database
          push: true
          tags: andrew2hill/nurs6293_database:${{ github.ref_name }}
